lang: en

page_title                                : Places                               # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6478914904                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/id6478914904                  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : /assets/PressKit.zip                      # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon512.png                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Places                               # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Download it for free!                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 'Pin your favorite places and share them with your friends'

# Apple Watch
enable_apple_watch                        : false                                      # Set to true to display an apple watch app image.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jorge Romanos                               
your_link                                 : https://xzebra.dev                     
your_city                                 : Spain                                
email_address                             : contact@visitplaces.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          :
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Pin your favorite places
    description                           : Add places and share them with a group.
    fontawesome_icon_name                 : pin
    
  - title                                 : Create lists
    description                           : You can create different lists  and share them with your friends.
    fontawesome_icon_name                 : object-group

  - title                                 : Mark as visited
    description                           : Mark places as visited and see how many places you have left to visit.
    fontawesome_icon_name                 : check

  - title                                 : Get details
    description                           : Get details about the place like address, phone number, website, etc.
    fontawesome_icon_name                 : info

  - title                                 : Share with friends
    description                           : Share places with your friends and keep track of their visits.
    fontawesome_icon_name                 : users

  - title                                 : Places history
    description                           : Past visited places can also be seen and reviewed.
    fontawesome_icon_name                 : list

  - title                                 : iCloud synchronization
    description                           : Automatic synchronization of the data between all your Apple devices (iPhone, iPad and Mac) thanks to iCloud.
    fontawesome_icon_name                 : cloud

  - title                                 : Offline mode
    description                           : Add or review places offline, sync changes when reconnected
    fontawesome_icon_name                 : plane

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.05
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.
watch_color                               : black                                     # Set to: black or white.

body_background_color                     : "#ffffff"

link_color                                : "#30b0c7"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#30b0c7"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"










####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
